# Generated by Django 4.1.3 on 2023-01-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='Cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='Product',
        ),
    ]
